apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

resources:
  - ../../base
  - pdb.yaml

patches:
  - path: patches/replicas.yaml
  - path: patches/resources.yaml
  - path: patches/anti-affinity.yaml

commonLabels:
  environment: production

images:
  - name: us-central1-docker.pkg.dev/PROJECT_ID/gitops-platform-images/frontend
    newTag: v1.0.0
  - name: us-central1-docker.pkg.dev/PROJECT_ID/gitops-platform-images/order-service
    newTag: v1.0.0
  - name: us-central1-docker.pkg.dev/PROJECT_ID/gitops-platform-images/product-service
    newTag: v1.0.0
