apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: platform-services
  namespace: monitoring
  labels:
    release: prometheus    # must match the Helm release name
spec:
  namespaceSelector:
    matchNames:
      - dev
  selector:
    matchLabels:
      tier: web
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
