apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - frontend/deployment.yaml
  - frontend/service.yaml
  - frontend/hpa.yaml
  - order-service/deployment.yaml
  - order-service/service.yaml
  - order-service/hpa.yaml
  - product-service/deployment.yaml
  - product-service/service.yaml
  - product-service/hpa.yaml
  - network-policies/default-deny.yaml
  - network-policies/app-policies.yaml
  - ingress/ingress.yaml
  - monitoring/servicemonitor.yaml

commonLabels:
  project: gitops-platform
  managed-by: argocd
