apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../../base

patches:
  - path: patches/replicas.yaml
  - path: patches/resources.yaml

commonLabels:
  environment: dev

images:
  - name: us-central1-docker.pkg.dev/PROJECT_ID/gitops-platform-images/frontend
    newTag: dev-latest
  - name: us-central1-docker.pkg.dev/PROJECT_ID/gitops-platform-images/order-service
    newTag: dev-latest
  - name: us-central1-docker.pkg.dev/PROJECT_ID/gitops-platform-images/product-service
    newTag: dev-latest
