apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
  - ../../base

patches:
  - path: patches/replicas.yaml

commonLabels:
  environment: staging

images:
  - name: us-central1-docker.pkg.dev/PROJECT_ID/gitops-platform-images/frontend
    newTag: staging-latest
  - name: us-central1-docker.pkg.dev/PROJECT_ID/gitops-platform-images/order-service
    newTag: staging-latest
  - name: us-central1-docker.pkg.dev/PROJECT_ID/gitops-platform-images/product-service
    newTag: staging-latest
